import "./App.css";
import React from "react";
import { Switch, BrowserRouter as Router, Route } from "react-router-dom";
import Frame2 from "./components/Frame2";
import InstagramStory1 from "./components/InstagramStory1";

function App() {
  return (
    <Router>
      <Switch>
        <Route path="/:path(|frame-2)">
          <Frame2 {...frame2Data} />
        </Route>
        <Route path="/instagram-story-1">
          <InstagramStory1 {...instagramStory1Data} />
        </Route>
      </Switch>
    </Router>
  );
}

export default App;
const frame2Data = {
    rectangle60: "/img/rectangle-60@1x.png",
    spanText1: "Somos uma ",
    spanText2: "Associação",
    spanText3: <> nascida em Blumenau, totalmente focada no bom relacionamento e economia do associado, levando segurança<br />e bem estar à nível nacional.</>,
    sendoAssimONosso: <>Sendo assim, o nosso compromisso de garantir proteção e tranquilidade é com você, associado, desempenhando um papel em conjunto através<br />da agilidade, qualidade e confiança, passa assim viver a vida que precisa.</>,
    spanText4: <>Abrimos as portas para todos que acreditam,<br />assim como nós, que possam ter a oportunidade<br />de possuir uma </>,
    spanText5: "proteção veicular",
    spanText6: " a um preço acessível, com isso, a ",
    spanText7: "única avaliação feita é do veículo",
    spanText8: <>, não considerando o perfil do condutor<br />nem consultas de crivo (SERASA/SPC).</>,
    reaDoAssociado: "Área do associado",
    benefcios1: "Benefícios",
    faaUmaCotao: "Faça uma cotação",
    curiosidade: "Curiosidade",
    sAMaxxTem: "Só a Maxx tem",
    ondeNosEncontrar: "Onde nos encontrar",
    depoimentos1: "Depoimentos",
    precisaDeAjuda: "Precisa de ajuda?",
    assistncia24HTelefone: "Assistência 24h: telefone",
    semTtulo11: "",
    muitoMais: "Muito mais",
    benefcios2: "benefícios",
    guinchoComKmIlimitado: <>Guincho com<br />km ilimitado</>,
    atR200MilContraTerceiros: <>Até R$ 200mil<br />contra terceiros</>,
    x100DeTabelaFipe: <>100% de<br />tabela FIPE</>,
    motoristaDaRodada1: <>Motorista<br />da rodada</>,
    chaveiroAuto: <>Chaveiro<br />Auto</>,
    seguroApp: <>Seguro<br />APP</>,
    martelinhoDeOuro: <>Martelinho<br />de ouro</>,
    motoReserva: <>Moto<br />Reserva</>,
    carroReserva: <>Carro<br />Reserva</>,
    apliceDanosMoraisEPessoais: <>Apólice danos<br />Morais e Pessoais</>,
    proteoDeMotorECmbio: <>Proteção de<br />motor e câmbio</>,
    retrovisoresEParaChoques: <>Retrovisores e<br />para-choques</>,
    transporteComKmIlimitada: <>Transporte com<br />km ilimitada</>,
    planoFuneral: <>Plano<br />Funeral</>,
    coberturaNacional: <>Cobertura<br />nacional</>,
    vidrosFarisELanternas: <>Vidros, faróis<br />e lanternas</>,
    quemSomos: "Quem somos?",
    faaUmaCotaoOnline: "Faça uma cotação online",
    faaUmaCotaoAgo: "Faça uma cotação agora mesmo e garanta a devida proteção para seu veículo.",
    nome: "Nome:",
    eMail: "E-mail:",
    whatsapp: "WhatsApp:",
    surprisedHappyBeardedManShirtPointi: "/img/surprised-happy-bearded-man-shirt-pointing-away-1@1x.png",
    image1: "/img/image-1@2x.png",
    text1: "1,",
    number: "99",
    aPartirDe: "A partir de",
    aoDia: "ao dia",
    vemDeMaxxEProtegeOSeuVeculo: <>Vem de Maxx<br />e protege o<br />seu veículo!</>,
    smilingFaceWithSunglasses1: "/img/smiling-face-with-sunglasses-1@1x.png",
    enviarDados: "Enviar Dados",
    semTtulo12: "",
    ellipse4: "/img/ellipse-4@1x.png",
    aMaxxTemGuinchoComKmIlimitada: "A Maxx tem guincho com km ilimitada",
    naMaxxProtegeVoc: "Na Maxx Protege você conta com o serviço de guincho e transporte com quilometragem ilimitada em casos de pane do veículo.",
    name: "Monte seu plano",
    prancheta11: "/img/prancheta-1-1@2x.png",
    naMaxxVocTem: "Na Maxx você tem",
    motoristaDaRodada2: <>Motorista<br />da rodada</>,
    guinchoETransporte: "Guincho e transporte com km ilimitada para pane",
    proteoParaMotorECmbio: <>Proteção para<br />motor e câmbio</>,
    x100DaTabelaFipe: <>100% da tabela<br />FIPE</>,
    depoimentos2: "Depoimentos",
    nomeSobrenome1: "Nome Sobrenome",
    loremIpsumDolorSi1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam",
    nomeSobrenome2: "Nome Sobrenome",
    loremIpsumDolorSi2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam",
    proteoVeicular: "PROTEÇÃO VEICULAR",
    matrizBlumenauSc: "Matriz - Blumenau/SC",
    rodPaulFritzKueh: <>Rod. Paul Fritz Kuehnrich, 990<br />Itoupava Norte</>,
    phone1: "(47) 3304-2028",
    vector112: "",
    blumenauSc1: "Blumenau/SC",
    rDrPedroZimmerm: <>R. Dr. Pedro Zimmermann, 2371<br />Itoupavazinha</>,
    spanText9: "(47) 98474-5597 ",
    spanText10: <>ou<br /></>,
    spanText11: "(47) 99672-3910",
    blumenauSc2: "Blumenau/SC",
    rFranciscoVahldieck2579Fortaleza: <>R. Francisco Vahldieck, 2579<br />Fortaleza</>,
    phone2: "(47) 99184-5050",
    blumenauSc3: "Blumenau/SC",
    rAmazona4160Sala02Garcia: <>R. Amazona, 4160 - Sala 02<br />Garcia</>,
    spanText12: "(47) 3288-9020 ",
    spanText13: <>ou <br /></>,
    spanText14: "(47) 99955-3249",
    brusqueSc: "Brusque/SC",
    rAlbertoKnop100JardimMaluche: <>R. Alberto Knop, 100<br />Jardim Maluche</>,
    spanText15: "(47) 3252-1686 ",
    spanText16: <>ou<br /></>,
    spanText17: "(47) 98839-9590 ",
    spanText18: "ou",
    spanText19: " 99672-3818",
    vector14: "",
    indaialSc: "Indaial/SC",
    avManoelSimo131Sala01Naes: <>Av. Manoel Simão, 131 - Sala 01<br />Nações</>,
    spanText20: "(47) 3387-2424 ",
    spanText21: <>ou<br /></>,
    spanText22: "(47) 99142-6211 ",
    spanText23: "ou",
    spanText24: " 98909-5401",
    ituporangaSc: "Ituporanga/SC",
    rVerglioScheller: <>R. Vergílio Scheller, 2140 - Sala 03<br />Gabiroba</>,
    spanText25: "(47) 99210-5541 ",
    spanText26: <>ou<br /></>,
    spanText27: "(47) 99969-1189",
    jaraguSc: "Jaraguá/SC",
    rCarlosEggert171VilaLalau: <>R. Carlos Eggert, 171<br />Vila Lalau</>,
    spanText28: "(47) 99602-8673 ",
    spanText29: <>ou<br /></>,
    spanText30: "(47) 99674-0015",
    taiSc: "Taió/SC",
    rCoronelFeddersen2120Centro: <>R. Coronel Feddersen, 2120<br />Centro</>,
    spanText31: "(47) 99627-4255 ",
    spanText32: <>ou<br /></>,
    spanText33: "(47) 99969-1167",
};

const smilingFaceWithSunglasses2Data = {
    className: "smiling-face-with-sunglasses-4",
};

const instagramStory1Data = {
    assistncia24HTelefone: "Assistência 24h: telefone",
    reaDoAssociado: "Área do associado",
    precisaDeAjuda: "Precisa de ajuda?",
    rectangle60: "/img/rectangle-60@1x.png",
    spanText1: "Somos uma ",
    spanText2: "Associação",
    spanText3: <> nascida em Blumenau, totalmente focada no bom relacionamento e economia do associado, levando segurança<br />e bem estar à nível nacional.</>,
    sendoAssimONosso: <>Sendo assim, o nosso compromisso de garantir proteção e tranquilidade é com você, associado, desempenhando um papel em conjunto através<br />da agilidade, qualidade e confiança, passa assim viver a vida que precisa.</>,
    spanText4: <>Abrimos as portas para todos que acreditam,<br />assim como nós, que possam ter a oportunidade<br />de possuir uma </>,
    spanText5: "proteção veicular",
    spanText6: " a um preço acessível, com isso, a ",
    spanText7: "única avaliação feita é do veículo",
    spanText8: <>, não considerando o perfil do condutor<br />nem consultas de crivo (SERASA/SPC).</>,
    semTtulo11: "",
    muitoMais: "Muito mais",
    benefcios: "benefícios",
    guinchoComKmIlimitado: <>Guincho com<br />km ilimitado</>,
    atR200MilContraTerceiros: <>Até R$ 200mil<br />contra terceiros</>,
    x100DeTabelaFipe: <>100% de<br />tabela FIPE</>,
    motoristaDaRodada1: <>Motorista<br />da rodada</>,
    chaveiroAuto: <>Chaveiro<br />Auto</>,
    seguroApp: <>Seguro<br />APP</>,
    martelinhoDeOuro: <>Martelinho<br />de ouro</>,
    motoReserva: <>Moto<br />Reserva</>,
    carroReserva: <>Carro<br />Reserva</>,
    apliceDanosMoraisEPessoais: <>Apólice danos<br />Morais e Pessoais</>,
    proteoDeMotorECmbio: <>Proteção de<br />motor e câmbio</>,
    retrovisoresEParaChoques: <>Retrovisores e<br />para-choques</>,
    transporteComKmIlimitada: <>Transporte com<br />km ilimitada</>,
    planoFuneral: <>Plano<br />Funeral</>,
    coberturaNacional: <>Cobertura<br />nacional</>,
    vidrosFarisELanternas: <>Vidros, faróis<br />e lanternas</>,
    quemSomos: "Quem somos?",
    faaUmaCotaoOnline: "Faça uma cotação online",
    faaUmaCotaoAgo: "Faça uma cotação agora mesmo e garanta a devida proteção para seu veículo.",
    nome: "Nome:",
    eMail: "E-mail:",
    whatsapp: "WhatsApp:",
    surprisedHappyBeardedManShirtPointi: "/img/surprised-happy-bearded-man-shirt-pointing-away-1@2x.png",
    image1: "/img/image-1@2x.png",
    text1: "1,",
    number: "99",
    aPartirDe: "A partir de",
    aoDia: "ao dia",
    vemDeMaxxEProtegeOSeuVeculo: <>Vem de Maxx<br />e protege o<br />seu veículo!</>,
    smilingFaceWithSunglasses1: "/img/smiling-face-with-sunglasses@1x.png",
    enviarDados: "Enviar Dados",
    semTtulo12: "",
    ellipse4: "/img/ellipse-4@2x.png",
    prancheta11: "/img/prancheta-1-1@2x.png",
    aMaxxTemGuinchoComKmIlimitada: "A Maxx tem guincho com km ilimitada",
    naMaxxProtegeVoc: "Na Maxx Protege você conta com o serviço de guincho e transporte com quilometragem ilimitada em casos de pane do veículo.",
    name: "Monte seu plano",
    naMaxxVocTem: "Na Maxx você tem",
    motoristaDaRodada2: <>Motorista<br />da rodada</>,
    guinchoETransporte: "Guincho e transporte com km ilimitada para pane",
    proteoParaMotorECmbio: <>Proteção para<br />motor e câmbio</>,
    x100DaTabelaFipe: <>100% da tabela<br />FIPE</>,
    depoimentos: "Depoimentos",
    nomeSobrenome1: "Nome Sobrenome",
    loremIpsumDolorSi1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam",
    nomeSobrenome2: "Nome Sobrenome",
    loremIpsumDolorSi2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam",
    proteoVeicular: "PROTEÇÃO VEICULAR",
    matrizBlumenauSc: "Matriz - Blumenau/SC",
    rodPaulFritzKueh: <>Rod. Paul Fritz Kuehnrich, 990<br />Itoupava Norte</>,
    phone1: "(47) 3304-2028",
    blumenauSc1: "Blumenau/SC",
    rDrPedroZimmerm: <>R. Dr. Pedro Zimmermann, 2371<br />Itoupavazinha</>,
    spanText9: "(47) 98474-5597 ",
    spanText10: <>ou<br /></>,
    spanText11: "(47) 99672-3910",
    blumenauSc2: "Blumenau/SC",
    rFranciscoVahldieck2579Fortaleza: <>R. Francisco Vahldieck, 2579<br />Fortaleza</>,
    phone2: "(47) 99184-5050",
    blumenauSc3: "Blumenau/SC",
    rAmazona4160Sala02Garcia: <>R. Amazona, 4160 - Sala 02<br />Garcia</>,
    spanText12: "(47) 3288-9020 ",
    spanText13: <>ou <br /></>,
    spanText14: "(47) 99955-3249",
    brusqueSc: "Brusque/SC",
    rAlbertoKnop100JardimMaluche: <>R. Alberto Knop, 100<br />Jardim Maluche</>,
    spanText15: "(47) 3252-1686 ",
    spanText16: <>ou<br /></>,
    spanText17: "(47) 98839-9590 ",
    spanText18: "ou",
    spanText19: " 99672-3818",
    indaialSc: "Indaial/SC",
    avManoelSimo131Sala01Naes: <>Av. Manoel Simão, 131 - Sala 01<br />Nações</>,
    spanText20: "(47) 3387-2424 ",
    spanText21: <>ou<br /></>,
    spanText22: "(47) 99142-6211 ",
    spanText23: "ou",
    spanText24: " 98909-5401",
    ituporangaSc: "Ituporanga/SC",
    rVerglioScheller: <>R. Vergílio Scheller, 2140 - Sala 03<br />Gabiroba</>,
    spanText25: "(47) 99210-5541 ",
    spanText26: <>ou<br /></>,
    spanText27: "(47) 99969-1189",
    jaraguSc: "Jaraguá/SC",
    rCarlosEggert171VilaLalau: <>R. Carlos Eggert, 171<br />Vila Lalau</>,
    spanText28: "(47) 99602-8673 ",
    spanText29: <>ou<br /></>,
    spanText30: "(47) 99674-0015",
    taiSc: "Taió/SC",
    rCoronelFeddersen2120Centro: <>R. Coronel Feddersen, 2120<br />Centro</>,
    spanText31: "(47) 99627-4255 ",
    spanText32: <>ou<br /></>,
    spanText33: "(47) 99969-1167",
    smilingFaceWithSunglassesProps: smilingFaceWithSunglasses2Data,
};

